/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#1a1a1a",
        "surface-container": "#eee9e0",
        "secondary": "#e63b2e",
        "on-secondary-fixed": "#1a1a1a",
        "primary": "#1a1a1a",
        "surface-container-high": "#e8e3da",
        "secondary-container": "#ffdad6",
        "primary-fixed": "#ffcc00",
        "inverse-on-surface": "#f5f0e8",
        "tertiary-fixed": "#d6e3ff",
        "inverse-primary": "#f5f0e8",
        "on-error": "#ffffff",
        "tertiary-container": "#d6e3ff",
        "on-surface-variant": "#4a4a4a",
        "surface-bright": "#faf7f2",
        "on-tertiary-fixed-variant": "#1a1a1a",
        "primary-container": "#ffcc00",
        "on-secondary-container": "#1a1a1a",
        "on-error-container": "#93000a",
        "error": "#cc0000",
        "outline": "#1a1a1a",
        "tertiary-fixed-dim": "#a8c6ff",
        "on-tertiary-container": "#1a1a1a",
        "secondary-fixed": "#ffdad6",
        "error-container": "#ffdad6",
        "surface-tint": "#1a1a1a",
        "on-primary-fixed": "#1a1a1a",
        "on-surface": "#1a1a1a",
        "surface-container-low": "#f2ede5",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2ddd4",
        "on-secondary-fixed-variant": "#1a1a1a",
        "surface-variant": "#e8e3da",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1a1a1a",
        "inverse-surface": "#1a1a1a",
        "background": "#f5f0e8",
        "surface-dim": "#d6d1c9",
        "tertiary": "#0055ff",
        "primary-fixed-dim": "#e6b800",
        "outline-variant": "#d0cbc3",
        "on-primary-fixed-variant": "#1a1a1a",
        "surface": "#f5f0e8",
        "secondary-fixed-dim": "#ffb3ab",
        "on-background": "#1a1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#1a1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
